name: manage-azure-policy-32403fe7
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policy/policies/Virtual_networks_should_be_protected_by_Azure_DDoS_Protection_Standard_94de2ad3-e0c1-4caf-ad78-5d47bbc83d3d/**'
#      - .github/workflows/manage-azure-policy-32403fe7.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_32403fe7}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policy/policies/Virtual_networks_should_be_protected_by_Azure_DDoS_Protection_Standard_94de2ad3-e0c1-4caf-ad78-5d47bbc83d3d/**
